### ISSUE TITLE
Publish version 0.9.2

### ISSUE THREAD

**Issue by ggrossetie** [anthonny/opal-npm-wrapper#10]
I've just released Opal 0.9.2 to the opal-cdn: https://github.com/opal/opal-cdn/tree/v0.9.2

**Comment by anthonny** [comment]
Done ;)

<img width="425" alt="capture d ecran 2016-04-05 a 09 24 50" src="https://cloud.githubusercontent.com/assets/2006548/14274281/aa4f8fc4-fb10-11e5-98b3-aa83fe090437.png">

<img width="310" alt="capture d ecran 2016-04-05 a 09 27 24" src="https://cloud.githubusercontent.com/assets/2006548/14274283/ad52305a-fb10-11e5-9a3d-9f940eeea4d3.png">

**Comment by ggrossetie** [comment]
Yay thanks :tada:
